### ISSUE TITLE
Endpoint not removed when 'docker rm -f' used

### ISSUE THREAD

**Issue by mbentley** [ehazlett/docker-havok#1]
I am not sure if this even it being monitored or not but when I use `docker rm -f <container>` to stop and remove a container, it is not picked up by havok and the endpoint remains.

**Comment by ehazlett** [comment]
So this looks like a race condition.  In docker, it's firing a kill which triggers the "die" event.  This is immediately followed by the "destroy" event which removes the container before havok can call an "Inspect" to read the container info to get ports, name, etc.  I think for now, don't do `rm -f`.

One solution would be to have a "cleanup" function that would periodically check the endpoints and their health.  I've been thinking of doing as part of a "self-healing" feature but I could easily add this as well.
